### ISSUE TITLE
Design + Content Needs

### ISSUE THREAD

**Issue by kvanderslice** [fiftyandfiftyorg/lifestraw-shopify#21]
# Design

### About Us 
- [x] Team images? Do we have them

### Give Back While You Shop
- [x] Need testimonial image for Chrispus & Ezra

### Outdoors (collections)
- [ ] Need all icons in the 'ideal for' section (experiencing issues when trying to export some for ex. the tent. It's causing the black box issue again). Also is there an icon set for these 'ideal for' sections for other pages?
- [ ] Is there an icon set for all potential 'removes' icons?

### Collections
- [x] Need icon set that represents the collections (outdoors, travel, daily etc.)

# Content
### Home
- [x] First slider link where does it go

### About Us
- [x] The three links at the bottom, are there going to be pages for those at time of launch? Do we have the content for them?
- [x] Content & Design discrepancy for three blocks section. In the design, it shows additional content on hover of the three blocks but the content doc does not include any additional content

### Doing Good
- [x] Donate Safe Water - link says it goes to the 'donate' page. We don't have a donate page and I don't see a general donation page for lifestraw on their current site. The donations are bucketed into projects so where should this link go for launch? Eugenia just provided a link in a basecamp message to Jacquie,  www.crowdrise.com/lifestraw . Is this where all donation related CTA's need to point to?

### Give Back While You Shop
- [x] Hero Video? Is it the video that is in the content doc for that page under 'Bringing Safe Water to the World'
- [x] Should all the testimonials have 'Stories from the students' as the subheading? There currently isn't any pages to direct users to on full story details as those won't be built in time for launch so I am omitting the buttons for now, just an FYI

### How our Products Work
- [x] Need the rest of the user manuals, only seeing one in basecamp. This is a Eugenia thing so need to get that from her?

### Footer

- [x] Need link destinations for 'Customer Support' and 'FAQ' - This is a Eugenia thing also, need intercom links from her for both

### Header Navigation
- [x] For shop now option 'reduces or removes', I need to know which products have which attached attribute. For now I pulled the list from the 'how our product works' page, but let me know if there is somewhere else that I should be referencing. Also for the tags of the category, would you prefer the tag to have 'reduces or removes' in the title (ex. reduces-or-removes-bacteria-and-parasites), or can it simply be the thing it filters (ex. bacteria-and-parasites)?

### Cart
- [x]  International Orders link URL? Eugenia, do you have a FAQ section about this, or a page that will outline more details on international ordering options?

### Social Share
- [x] Need language for facebook and twitter social share on doing good and giving back through retail

### Home
- [x] Need an image for the last slide
- [x] Need the image for the blue background section

- [x] Give Back Map section icon for filters delivered

### How our Products Work
- [x] Need better logos for the schools, you can see the outlines of them

### Blog
- [x] Doesn't function like a wordpress blog, so you can archive categories but the design with the 'featured', 'recent', etc. is not an option at this time. Potentially doable with another app

- [x] Doing Good video for hero?

**Comment by javanvg** [comment]
**Home**
- [ ] Slide 3 - https://www.dropbox.com/s/5fcplif5912t62a/home-hdr-slide-3.jpg?dl=0
- [ ] Bottle on Blue - https://www.dropbox.com/s/gk3ka19mn4kmxlf/bottle-home-white%402x.png?dl=0

**About Us**
No images provided. Let's ask Eugenia to add those if that's ok. They were all low res from their site.

**Doing Good**
- [ ] Video: https://www.youtube.com/watch?time_continue=17&v=Jh2enp6ReO0

**Give Back**
- [ ]  Filter icon: https://www.dropbox.com/s/3oqb41cg7h7jpl7/icon-filter-white.svg?dl=0
- [ ] Chrispus & Ezra: Let's have Eugenia source these? I don't know where they are

**How Products Work**
- [ ] School logos: I tried finding these but can't find much better. I made them blue background and dealt with the border issue. Are they still blurry?

**Outdoor**
- [ ] Icons: Here are the ones I have in the comp. I'm assuming Eugenia will come up with more categories later but if not, I just need a full list of these and I'll find an icon for everything.
Backpacking - https://www.dropbox.com/s/epqxutj1bey8gqp/icon-backbacking.svg?dl=0
Camping - https://www.dropbox.com/s/9vbhl4a65jrvozm/icon-camping.svg?dl=0
Hiking - https://www.dropbox.com/s/j9zjpss90g9nd4b/icon-hiking.svg?dl=0
Recreation - https://www.dropbox.com/s/jhoxcxb6jp1fbru/icon-recreation.svg?dl=0
- [ ] Icons for 'removes....': I'd use the icons we put in the nav as it seems the most complete. https://www.dropbox.com/s/ee7b1ctw89x7d6b/Nav-Dropdowns.psb?dl=0

**Blog**
Noted
