### ISSUE TITLE
Product Detail - Video Icon first in rotator and update arrows

### ISSUE THREAD

**Issue by javanvg** [fiftyandfiftyorg/lifestraw-shopify#28]
Lets move the video to first in the slideshow and use the play icon as the thumbnail...

![image](https://user-images.githubusercontent.com/237413/48213921-b1c33e00-e333-11e8-9c8d-7476ecbf7007.png)

Let's also update the arrows to the chevron style used everywhere else.

**Comment by kvanderslice** [comment]
Was able to append it as the fourth item in the slider after all
